spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=thebooks;encrypt=false;trustServerCertificate=true;integratedSecurity=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=com.example.bookreading.config.CustomPhysicalNamingStrategy
spring.jpa.open-in-view=false
server.port=8080
spring.web.resources.static-locations=classpath:/static/,file:./
spring.sql.init.mode=never
